name: Electron Master

defaults:
  run:
    shell: bash

env:
  CI: true

on:
  push:
    tags:
      - v**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    # this is so the assets can be added to the release
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: pip.exe install setuptools
      - name: Process release version
        id: process_version
        run: |
          echo "version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Build Electron
        run: ./bin/package-electron
      - name: Upload Build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: actual-electron-windows
          path: |
            packages/desktop-electron/dist/*.exe
            !packages/desktop-electron/dist/Actual-windows.exe
            packages/desktop-electron/dist/*.yml
            !packages/desktop-electron/dist/builder-*.yml
      - name: Add to new release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          draft: true
          body: |
            ## Desktop release v${{ steps.process_version.outputs.version }}
          files: |
            packages/desktop-electron/dist/*.exe
            !packages/desktop-electron/dist/Actual-windows.exe
            packages/desktop-electron/dist/*.yml
            !packages/desktop-electron/dist/builder-*.yml
